### ISSUE TITLE
ValueError: Negative dimension size caused by subtracting 3 from 1 for 'conv2d_2/convolution' (op: 'Conv2D') with input shapes: [?,1,78,32], [3,3,32,32]

### ISSUE THREAD

**Issue by xxoxx** [FanhuaandLuomu/captcha_break_keras#1]
[[root@MyVps captcha_break_keras]# python2.7 captcha_test.py 
0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
Using TensorFlow backend.
captcha_test.py:64: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), activation="relu")`
  x=Convolution2D(32*2**i,3,3,activation='relu')(x)
captcha_test.py:65: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), activation="relu")`
  x=Convolution2D(32*2**i,3,3,activation='relu')(x)
Traceback (most recent call last):
  File "captcha_test.py", line 65, in <module>
    x=Convolution2D(32*2**i,3,3,activation='relu')(x)
  File "/root/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/keras/layers/convolutional.py", line 164, in call
    dilation_rate=self.dilation_rate)
  File "/root/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 3138, in conv2d
    data_format='NHWC')
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 670, in convolution
    op=op)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 338, in with_space_to_batch
    return op(input, num_spatial_dims, padding)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 662, in op
    name=name)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 131, in _non_atrous_convolution
    name=name)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 399, in conv2d
    data_format=data_format, name=name)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 3 from 1 for 'conv2d_2/convolution' (op: 'Conv2D') with input shapes: [?,1,78,32], [3,3,32,32].
](url)

**Comment by xxoxx** [comment]
Centos6.8
Anaconda python2.7.13

**Comment by qchai** [comment]
0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
Using TensorFlow backend.
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 654, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "D:\Anaconda\lib\contextlib.py", line 89, in __exit__
    next(self.gen)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 3 from 1 for 'conv2d_2/convolution' (op: 'Conv2D') with input shapes: [?,1,78,32], [3,3,32,32].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/qchai/Downloads/captcha_break_keras-master/captcha_break_keras-master/captcha_test.py", line 64, in <module>
    x = Conv2D(32 * 2 ** i, (3, 3), activation='relu')(x)
  File "D:\Anaconda\lib\site-packages\keras\engine\topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "D:\Anaconda\lib\site-packages\keras\layers\convolutional.py", line 164, in call
    dilation_rate=self.dilation_rate)
  File "D:\Anaconda\lib\site-packages\keras\backend\tensorflow_backend.py", line 3164, in conv2d
    data_format='NHWC')
  File "D:\Anaconda\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 672, in convolution
    op=op)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 338, in with_space_to_batch
    return op(input, num_spatial_dims, padding)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 664, in op
    name=name)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 131, in _non_atrous_convolution
    name=name)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 397, in conv2d
    data_format=data_format, name=name)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 2632, in create_op
    set_shapes_for_outputs(ret)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1911, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1861, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 595, in call_cpp_shape_fn
    require_shape_fn)
  File "D:\Anaconda\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 659, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 3 from 1 for 'conv2d_2/convolution' (op: 'Conv2D') with input shapes: [?,1,78,32], [3,3,32,32].

Process finished with exit code 1
遇到了同样的问题，麻烦帮忙看一下，谢谢

**Comment by yinhao0214** [comment]
不好意思，忘了说明了。我的代码基于py2.7+theano+keras1.2。@qchai @xxoxx
